### ISSUE TITLE
字号的设置有误

### ISSUE THREAD

**Issue by zepinglee** [heywrcoding/UESTC_Lab_Report_LaTeX_Template#3]
1. 直接 `\setlength{\baselineskip}{20pt}` 会被 \normalsize 等命令覆盖
2. `\fontsize{12pt}{\baselineskip}\selectfont` 这样设置的行距是错的

**Comment by zshufan** [comment]
您好，谢谢您的指正！
我最初的想法是，改变基本行间距为20磅（这个是否相当于word里面的“固定值” 20磅？），然后通过设定字号的baselineskip来设置linespace。
您的意思是否是：
\fontsize命令无法更改字号宏\f@size中对于\f@baselineskip的定义？
那是否应该使用修改因子的方式来修改间距，而非通过修改基本间距的方式？

您是否可以留下您的QQ呢？我希望可以更详细地得到您的指点！

**Comment by zepinglee** [comment]
> \fontsize命令无法更改字号宏\f@size中对于\f@baselineskip的定义

可以更改，但是这个更改是局部的，会被其他 \normalsize \small 等字号命令会覆盖掉

qq 1034603881
